# 124 classes, trained on Mapillvary v2
MMLAB_CONFIG = dict(
        classes=('Bird', 'Ground Animal', 'Curb', 'Fence', 'Guard Rail',
                 'Barrier', 'Wall', 'Bike Lane', 'Crosswalk - Plain',
                 'Curb Cut', 'Parking', 'Pedestrian Area', 'Rail Track',
                 'Road', 'Service Lane', 'Sidewalk', 'Bridge', 'Building',
                 'Tunnel', 'Person', 'Bicyclist', 'Motorcyclist',
                 'Other Rider', 'Lane Marking - Crosswalk',
                 'Lane Marking - General', 'Mountain', 'Sand', 'Sky', 'Snow',
                 'Terrain', 'Vegetation', 'Water', 'Banner', 'Bench',
                 'Bike Rack', 'Billboard', 'Catch Basin', 'CCTV Camera',
                 'Fire Hydrant', 'Junction Box', 'Mailbox', 'Manhole',
                 'Phone Booth', 'Pothole', 'Street Light', 'Pole',
                 'Traffic Sign Frame', 'Utility Pole', 'Traffic Light',
                 'Traffic Sign (Back)', 'Traffic Sign (Front)', 'Trash Can',
                 'Bicycle', 'Boat', 'Bus', 'Car', 'Caravan', 'Motorcycle',
                 'On Rails', 'Other Vehicle', 'Trailer', 'Truck',
                 'Wheeled Slow', 'Car Mount', 'Ego Vehicle', 'Unlabeled'),
        palette=[[165, 42, 42], [0, 192, 0], [196, 196, 196], [190, 153, 153],
                 [180, 165, 180], [90, 120, 150], [102, 102, 156],
                 [128, 64, 255], [140, 140, 200], [170, 170, 170],
                 [250, 170, 160], [96, 96, 96],
                 [230, 150, 140], [128, 64, 128], [110, 110, 110],
                 [244, 35, 232], [150, 100, 100], [70, 70, 70], [150, 120, 90],
                 [220, 20, 60], [255, 0, 0], [255, 0, 100], [255, 0, 200],
                 [200, 128, 128], [255, 255, 255], [64, 170,
                                                    64], [230, 160, 50],
                 [70, 130, 180], [190, 255, 255], [152, 251, 152],
                 [107, 142, 35], [0, 170, 30], [255, 255, 128], [250, 0, 30],
                 [100, 140, 180], [220, 220, 220], [220, 128, 128],
                 [222, 40, 40], [100, 170, 30], [40, 40, 40], [33, 33, 33],
                 [100, 128, 160], [142, 0, 0], [70, 100, 150], [210, 170, 100],
                 [153, 153, 153], [128, 128, 128], [0, 0, 80], [250, 170, 30],
                 [192, 192, 192], [220, 220, 0], [140, 140, 20], [119, 11, 32],
                 [150, 0, 255], [0, 60, 100], [0, 0, 142], [0, 0, 90],
                 [0, 0, 230], [0, 80, 100], [128, 64, 64], [0, 0, 110],
                 [0, 0, 70], [0, 0, 192], [32, 32, 32], [120, 10,
                                                         10], [0, 0, 0]])

# 64 classes, trained on Mapillvary v1
# https://github.com/facebookresearch/Mask2Former/blob/main/mask2former/data/datasets/register_mapillary_vistas.py
FB_CONFIG = [
    {
        "color": [165, 42, 42],
        "instances": True,
        "readable": "Bird",
        "name": "animal--bird",
        "evaluate": True,
    },
    {
        "color": [0, 192, 0],
        "instances": True,
        "readable": "Ground Animal",
        "name": "animal--ground-animal",
        "evaluate": True,
    },
    {
        "color": [196, 196, 196],
        "instances": False,
        "readable": "Curb",
        "name": "construction--barrier--curb",
        "evaluate": True,
    },
    {
        "color": [190, 153, 153],
        "instances": False,
        "readable": "Fence",
        "name": "construction--barrier--fence",
        "evaluate": True,
    },
    {
        "color": [180, 165, 180],
        "instances": False,
        "readable": "Guard Rail",
        "name": "construction--barrier--guard-rail",
        "evaluate": True,
    },
    {
        "color": [90, 120, 150],
        "instances": False,
        "readable": "Barrier",
        "name": "construction--barrier--other-barrier",
        "evaluate": True,
    },
    {
        "color": [102, 102, 156],
        "instances": False,
        "readable": "Wall",
        "name": "construction--barrier--wall",
        "evaluate": True,
    },
    {
        "color": [128, 64, 255],
        "instances": False,
        "readable": "Bike Lane",
        "name": "construction--flat--bike-lane",
        "evaluate": True,
    },
    {
        "color": [140, 140, 200],
        "instances": True,
        "readable": "Crosswalk - Plain",
        "name": "construction--flat--crosswalk-plain",
        "evaluate": True,
    },
    {
        "color": [170, 170, 170],
        "instances": False,
        "readable": "Curb Cut",
        "name": "construction--flat--curb-cut",
        "evaluate": True,
    },
    {
        "color": [250, 170, 160],
        "instances": False,
        "readable": "Parking",
        "name": "construction--flat--parking",
        "evaluate": True,
    },
    {
        "color": [96, 96, 96],
        "instances": False,
        "readable": "Pedestrian Area",
        "name": "construction--flat--pedestrian-area",
        "evaluate": True,
    },
    {
        "color": [230, 150, 140],
        "instances": False,
        "readable": "Rail Track",
        "name": "construction--flat--rail-track",
        "evaluate": True,
    },
    {
        "color": [128, 64, 128],
        "instances": False,
        "readable": "Road",
        "name": "construction--flat--road",
        "evaluate": True,
    },
    {
        "color": [110, 110, 110],
        "instances": False,
        "readable": "Service Lane",
        "name": "construction--flat--service-lane",
        "evaluate": True,
    },
    {
        "color": [244, 35, 232],
        "instances": False,
        "readable": "Sidewalk",
        "name": "construction--flat--sidewalk",
        "evaluate": True,
    },
    {
        "color": [150, 100, 100],
        "instances": False,
        "readable": "Bridge",
        "name": "construction--structure--bridge",
        "evaluate": True,
    },
    {
        "color": [70, 70, 70],
        "instances": False,
        "readable": "Building",
        "name": "construction--structure--building",
        "evaluate": True,
    },
    {
        "color": [150, 120, 90],
        "instances": False,
        "readable": "Tunnel",
        "name": "construction--structure--tunnel",
        "evaluate": True,
    },
    {
        "color": [220, 20, 60],
        "instances": True,
        "readable": "Person",
        "name": "human--person",
        "evaluate": True,
    },
    {
        "color": [255, 0, 0],
        "instances": True,
        "readable": "Bicyclist",
        "name": "human--rider--bicyclist",
        "evaluate": True,
    },
    {
        "color": [255, 0, 100],
        "instances": True,
        "readable": "Motorcyclist",
        "name": "human--rider--motorcyclist",
        "evaluate": True,
    },
    {
        "color": [255, 0, 200],
        "instances": True,
        "readable": "Other Rider",
        "name": "human--rider--other-rider",
        "evaluate": True,
    },
    {
        "color": [200, 128, 128],
        "instances": True,
        "readable": "Lane Marking - Crosswalk",
        "name": "marking--crosswalk-zebra",
        "evaluate": True,
    },
    {
        "color": [255, 255, 255],
        "instances": False,
        "readable": "Lane Marking - General",
        "name": "marking--general",
        "evaluate": True,
    },
    {
        "color": [64, 170, 64],
        "instances": False,
        "readable": "Mountain",
        "name": "nature--mountain",
        "evaluate": True,
    },
    {
        "color": [230, 160, 50],
        "instances": False,
        "readable": "Sand",
        "name": "nature--sand",
        "evaluate": True,
    },
    {
        "color": [70, 130, 180],
        "instances": False,
        "readable": "Sky",
        "name": "nature--sky",
        "evaluate": True,
    },
    {
        "color": [190, 255, 255],
        "instances": False,
        "readable": "Snow",
        "name": "nature--snow",
        "evaluate": True,
    },
    {
        "color": [152, 251, 152],
        "instances": False,
        "readable": "Terrain",
        "name": "nature--terrain",
        "evaluate": True,
    },
    {
        "color": [107, 142, 35],
        "instances": False,
        "readable": "Vegetation",
        "name": "nature--vegetation",
        "evaluate": True,
    },
    {
        "color": [0, 170, 30],
        "instances": False,
        "readable": "Water",
        "name": "nature--water",
        "evaluate": True,
    },
    {
        "color": [255, 255, 128],
        "instances": True,
        "readable": "Banner",
        "name": "object--banner",
        "evaluate": True,
    },
    {
        "color": [250, 0, 30],
        "instances": True,
        "readable": "Bench",
        "name": "object--bench",
        "evaluate": True,
    },
    {
        "color": [100, 140, 180],
        "instances": True,
        "readable": "Bike Rack",
        "name": "object--bike-rack",
        "evaluate": True,
    },
    {
        "color": [220, 220, 220],
        "instances": True,
        "readable": "Billboard",
        "name": "object--billboard",
        "evaluate": True,
    },
    {
        "color": [220, 128, 128],
        "instances": True,
        "readable": "Catch Basin",
        "name": "object--catch-basin",
        "evaluate": True,
    },
    {
        "color": [222, 40, 40],
        "instances": True,
        "readable": "CCTV Camera",
        "name": "object--cctv-camera",
        "evaluate": True,
    },
    {
        "color": [100, 170, 30],
        "instances": True,
        "readable": "Fire Hydrant",
        "name": "object--fire-hydrant",
        "evaluate": True,
    },
    {
        "color": [40, 40, 40],
        "instances": True,
        "readable": "Junction Box",
        "name": "object--junction-box",
        "evaluate": True,
    },
    {
        "color": [33, 33, 33],
        "instances": True,
        "readable": "Mailbox",
        "name": "object--mailbox",
        "evaluate": True,
    },
    {
        "color": [100, 128, 160],
        "instances": True,
        "readable": "Manhole",
        "name": "object--manhole",
        "evaluate": True,
    },
    {
        "color": [142, 0, 0],
        "instances": True,
        "readable": "Phone Booth",
        "name": "object--phone-booth",
        "evaluate": True,
    },
    {
        "color": [70, 100, 150],
        "instances": False,
        "readable": "Pothole",
        "name": "object--pothole",
        "evaluate": True,
    },
    {
        "color": [210, 170, 100],
        "instances": True,
        "readable": "Street Light",
        "name": "object--street-light",
        "evaluate": True,
    },
    {
        "color": [153, 153, 153],
        "instances": True,
        "readable": "Pole",
        "name": "object--support--pole",
        "evaluate": True,
    },
    {
        "color": [128, 128, 128],
        "instances": True,
        "readable": "Traffic Sign Frame",
        "name": "object--support--traffic-sign-frame",
        "evaluate": True,
    },
    {
        "color": [0, 0, 80],
        "instances": True,
        "readable": "Utility Pole",
        "name": "object--support--utility-pole",
        "evaluate": True,
    },
    {
        "color": [250, 170, 30],
        "instances": True,
        "readable": "Traffic Light",
        "name": "object--traffic-light",
        "evaluate": True,
    },
    {
        "color": [192, 192, 192],
        "instances": True,
        "readable": "Traffic Sign (Back)",
        "name": "object--traffic-sign--back",
        "evaluate": True,
    },
    {
        "color": [220, 220, 0],
        "instances": True,
        "readable": "Traffic Sign (Front)",
        "name": "object--traffic-sign--front",
        "evaluate": True,
    },
    {
        "color": [140, 140, 20],
        "instances": True,
        "readable": "Trash Can",
        "name": "object--trash-can",
        "evaluate": True,
    },
    {
        "color": [119, 11, 32],
        "instances": True,
        "readable": "Bicycle",
        "name": "object--vehicle--bicycle",
        "evaluate": True,
    },
    {
        "color": [150, 0, 255],
        "instances": True,
        "readable": "Boat",
        "name": "object--vehicle--boat",
        "evaluate": True,
    },
    {
        "color": [0, 60, 100],
        "instances": True,
        "readable": "Bus",
        "name": "object--vehicle--bus",
        "evaluate": True,
    },
    {
        "color": [0, 0, 142],
        "instances": True,
        "readable": "Car",
        "name": "object--vehicle--car",
        "evaluate": True,
    },
    {
        "color": [0, 0, 90],
        "instances": True,
        "readable": "Caravan",
        "name": "object--vehicle--caravan",
        "evaluate": True,
    },
    {
        "color": [0, 0, 230],
        "instances": True,
        "readable": "Motorcycle",
        "name": "object--vehicle--motorcycle",
        "evaluate": True,
    },
    {
        "color": [0, 80, 100],
        "instances": False,
        "readable": "On Rails",
        "name": "object--vehicle--on-rails",
        "evaluate": True,
    },
    {
        "color": [128, 64, 64],
        "instances": True,
        "readable": "Other Vehicle",
        "name": "object--vehicle--other-vehicle",
        "evaluate": True,
    },
    {
        "color": [0, 0, 110],
        "instances": True,
        "readable": "Trailer",
        "name": "object--vehicle--trailer",
        "evaluate": True,
    },
    {
        "color": [0, 0, 70],
        "instances": True,
        "readable": "Truck",
        "name": "object--vehicle--truck",
        "evaluate": True,
    },
    {
        "color": [0, 0, 192],
        "instances": True,
        "readable": "Wheeled Slow",
        "name": "object--vehicle--wheeled-slow",
        "evaluate": True,
    },
    {
        "color": [32, 32, 32],
        "instances": False,
        "readable": "Car Mount",
        "name": "void--car-mount",
        "evaluate": True,
    },
    {
        "color": [120, 10, 10],
        "instances": False,
        "readable": "Ego Vehicle",
        "name": "void--ego-vehicle",
        "evaluate": True,
    },
    {
        "color": [0, 0, 0],
        "instances": False,
        "readable": "Unlabeled",
        "name": "void--unlabeled",
        "evaluate": False,
    },
]


MAPILLARY_DESCRIPTION = {
    "Curb": "Raised (>3cm) formation typically between road and sidewalk or terrain. Includes the brick’s horizontal and vertical surface. If there is no clear border between sidewalk/terrain and curb, only the vertical surface is labeled.",
    "Fence": "Freestanding structure with holes that separate two (or more) outdoor areas, sometimes temporary ones.",
    "Guard Rail": "Metal structure mounted on the side of the road to prevent serious accidents. Includes the bars holding the rails.",
    "Barrier": "Fallback category for other forms of barriers, e.g. lane separator, jersey barrier.",
    "Wall": "Individually standing walls that separate two (or more) outdoor areas, and do not provide support for a building. Includes transparent walls.",
    "Bike Lane": "Paved areas intended for bicycle use only. Does not include regions meant to be used by both cyclists and pedestrians. Regions of road intended for mixed cycle and car use are labeled as road. Contains only regions of ground speciﬁcally designated for cyclists where pedestrians and cars should not enter, e.g. separated by curb or lane markings (dashed or driveable).",
    "Crosswalk - Plain": "Region of a road which is meant to cross the street but not marked with a zebra pattern, instead two parallel lines indicate the crosswalk. The road surface is marked as plain crosswalk, the two lines indicating the border are marked as general markings.",
    "Curb Cut": "Lowered curbs (≈3cm) or curb cuts (<3cm) which can be driven over, e.g. by wheelchairs.",
    "Parking": "Surfaces that are intended for parking and separated from the road either via elevation or different texture/material or lane markings. Only the area which is available for parking has to be annotated. Flat areas used to get on a speciﬁc parking slot need to be labeled as road.",
    "Pedestrian Area": "Areas solely to be used by pedestrians. E.g. in inner city areas or parks, shopping zones, etc.",
    "Rail Track": "Horizontal surface on which rail cars typically drive. If rail-tracks are embedded in a conventional road block, the rail track is drawn on top of a road label.",
    "Road": "Surface on which cars usually drive on. Typically delimited by curbs, parking areas or bicycle lanes.",
    "Service Lane": "Road shoulders, typically on highways, which offer enough space for a car to drive and stop in emergency cases. Usually on the right side of drivable lanes (viewed in driving direction, in case of right-hand trafﬁc), but can also be on the left side.",
    "Sidewalk": "Horizontal surface designated for pedestrians or cyclists. Delimited from the road by some obstacles, e.g. curbs (raised or lowered) or poles, but not only by marking. Often elevated compared to the road and often located at the side of a road. Also includes walkable parts of trafﬁc islands, but not pedestrian areas.",
    "Bridge": "Bridges (on which the ego-vehicle is not driving) including everything (fences, guard rails) permanently attached to them.",
    "Building": "Includes structures that house/shelter humans, e.g. low-rises, skyscrapers, bus stops, carports. Translucent buildings made of glass still receive the label building. Also includes scaffolding attached to buildings.",
    "Tunnel": "Tunnel walls and the dark space encased by the tunnel, but excluding vehicles.",
    "Lane Marking - Crosswalk": "Crosswalk indicated by a zebra pattern.",
    "Lane Marking - General": "Other lane markings including dashed and solid lane separation markings, stop lines, text, arrows or restricted areas.",
    "Catch Basin": "Sewage water drainage, typically with a grid on top or inlet of a curb.",
    "Fire Hydrant": "Water outlet typically used by ﬁre-ﬁghters.",
    "Junction Box": "An electrical junction box can contain junctions of electric wires and/or cables.",
    "Manhole": "Opening in road to access canal system. Has to be big enough to ﬁt a person and includes squared ones.",
    "Pothole": "A depression or hollow in a road caused by wear or subsidence.",
    "Street Light": "Lights mounted on poles to illuminate the road or public places.",
    "Pole": "Thin and elongated, typically vertically oriented poles, e.g. sign or trafﬁc light poles. Does not include objects mounted on the pole. Poles holding only street lights should also be labeled as pole.",
    "Traffic Sign Frame": "Frame construction holding large signs, where frame can be made of round or square poles. Can be typically found on highways.",
    "Utility Pole": "Utility poles are supposed to carry electrical wires/cables, could be used to mount mobile phone network receivers, and are used in case both, cables and street lights are mounted.",
    "Traffic Light": "Trafﬁc lights without poles in different orientations (upright, horizontal, side, back, front) and for all types of trafﬁc participants, e.g. regular trafﬁc light, bus trafﬁc light, train trafﬁc light. If the type can be determined but does not match any of the deﬁned categories (e.g. trafﬁc lights for trains), then trafﬁc light - other is used. If the orientation or type of trafﬁc light cannot be determined, trafﬁc light - ambiguous is used.",
    "Traffic Sign (Back)": "Back side of trafﬁc signs.",
    "Traffic Sign (Front)": "Signs with the purpose of conveying information to drivers/cyclists/pedestrians, e.g. trafﬁc signs or warning reﬂector posts. If the type of a frontviewed trafﬁc sign cannot be determined, e.g. because of unknown language, trafﬁc sign - unknown is used as fallback.",
    "Trash Can": "Recycling facility for waste collection.",
    "Animal": "",
    "Person": "People moving, sitting, in any pose; or riding any vehicle, bicyclist, motorcyclist, other rider",
    # "Bicyclist": "Humans driving a bicycle. Does not include the bicycle or persons moving a bike while walking.",
    # "Motorcyclist": "Person riding a motorcycle without the motorcycle, includes passengers.",
    # "Other Rider": "People riding other types of vehicles like rickshaw, wheeled chair, scooter, mobility-scooter.",
    "Mountain": "Distant elevations of the ground.",
    "Sand": "Includes surfaces consisting of sand or sand heaps, e.g. at construction areas.",
    "Sky": "Sky including fog or heavy precipitation.",
    "Snow": "Snow covered surfaces.",
    "Terrain": "Grass and all other types of horizontal spreading vegetation, includes soil.",
    "Vegetation": "Trees and other forms of vertical growing vegetation.",
    "Water": "Ground surfaces covered by water.",
    "Banner": "Typically a ﬂag, made of textile or plastic.",
    "Bench": "A place to sit down.",
    "Bike Rack": "A construction to place and lock a bike.",
    "Billboard": "Advertisements placed in public space and also those mounted on buildings.",
    "CCTV Camera": "Surveillance camera mounted in public space",
    "Mailbox": "A box to put mail into.",
    "Phone Booth": "A public call box typically equipped with a payphone.",
    "Bicycle": "Includes bicycles without the cyclist or possibly other passengers. The cyclist and passengers receive label cyclist.",
    "Boat": "Vehicle suitable for riding/sailing on water.",
    "Bus": "Includes buses that are intended for 9+ persons for public or long-distance transport.",
    "Car": "This includes cars, jeeps, SUVs, vans with a continuous body shape (i.e. the driver cabin and cargo compartment are one).",
    "Caravan": "Vehicles that (appear to) contain living quarters. This also includes trailers that are used for living and has priority over the trailer class.",
    "Motorcycle": "This includes motorcycles, mopeds without the driver or other passengers. Both driver and passengers receive the label motorcyclist.",
    "On Rails": "All vehicles moving on rails, e.g. trams, trains.",
    "Other Vehicle": "Fallback category for vehicles not explicitly deﬁned otherwise in meta category level vehicle.",
    "Trailer": "Trailers that can be attached to any vehicle, but excludes trailers attached to trucks. The latter belong to class truck.",
    "Truck": "This includes trucks, vans with a body that is separate from the driver cabin, pickup trucks, as well as their attached trailers.",
    "Wheeled Slow": "Covers all slow moving wheeled objects like wheelchairs, mobility-scooters, scooters, prams or rickshaw. All of which can potentially have riders (other rider) sitting on them, similar to cycles are driven by cyclists.",
    "Car Mount": "Mount used to hold the camera while capturing.",
    "Ego Vehicle": "Ego-vehicle, e.g. car hood, dashboard, driving mirror."
}

LLM_DESCRIPTION = {
    "claude": {
        "Curb": "Elevated boundary (>3cm) between road and sidewalk. Concrete/stone ridge with vertical face and flat top. Gray, forming continuous line along streets. Creates visible shadow line.",
        "Fence": "Freestanding structure with gaps/holes separating outdoor areas. Various materials (chain-link, wood, metal). Typically linear with regular pattern.",
        "Guard Rail": "Metal protective structure along roadside. Horizontal silver/gray rails with vertical supports. Often curved or W-shaped profile.",
        "Barrier": "Temporary or permanent divider between areas. Includes concrete jersey barriers, plastic dividers, bollards. Often brightly colored or reflective.",
        "Wall": "Freestanding vertical structure separating outdoor areas. Solid surface without openings. Brick, concrete, or stone. Not supporting buildings.",
        "Bike Lane": "Designated path for bicycles. Often colored green/red or marked with bicycle symbols. Separated by painted lines or physical barriers from vehicular lanes.",
        "Crosswalk - Plain": "Road crossing area marked by two parallel lines without zebra pattern. Connects sidewalks across streets for pedestrian crossing.",
        "Curb Cut": "Lowered section (<3cm) of curb forming ramp. Creates smooth transition between road and sidewalk. Often at intersections and driveways.",
        "Parking": "Designated vehicle storage area. Separated from road by lines, texture differences or elevation. Often marked with P signs or painted boundaries.",
        "Pedestrian Area": "Paved zones exclusively for walking. Often brick/tile surfaces in plazas, malls, parks. No vehicle access. May have benches, planters.",
        "Rail Track": "Linear metal rails for trains/trams. Parallel metal strips embedded in or raised above ground. Often with wooden/concrete ties between rails.",
        "Road": "Paved surface for vehicles. Asphalt/concrete, typically dark gray with lane markings. Bordered by curbs, sidewalks or shoulders.",
        "Service Lane": "Auxiliary roadway alongside main highway. Narrower than main lanes, often separated by markings. For emergency stopping or service vehicles.",
        "Sidewalk": "Pedestrian path adjacent to roads. Elevated surface, typically concrete/brick/paver stones. Often lighter color than road surface.",
        "Bridge": "Elevated structure spanning gap/waterway. Visible supports/railings. Includes attached elements like fences and guard rails.",
        "Building": "Permanent structure with walls/roof. Various sizes from sheds to skyscrapers. Includes glass structures, bus shelters, and attached scaffolding.",
        "Tunnel": "Enclosed passage through obstacle. Dark interior with walls/ceiling. Artificial lighting and ventilation systems visible.",
        "Lane Marking - Crosswalk": "Road marking with alternating white stripes (zebra pattern). Perpendicular to traffic flow, connecting sidewalks.",
        "Lane Marking - General": "Painted road symbols including lines, arrows, text, stop lines. White or yellow, painted directly on road surface.",
        "Catch Basin": "Street drainage opening. Metal grate or curb inlet. Rectangular or round shape embedded in road/sidewalk.",
        "Fire Hydrant": "Water connection for firefighting. Compact metal fixture on sidewalks. Typically red/yellow, mushroom or pillar shaped with caps/outlets.",
        "Junction Box": "Utility cabinet housing electrical connections. Metal/plastic box mounted on ground or pole. Often gray/green with access panel.",
        "Manhole": "Access cover to underground utilities. Round/square metal plate with patterns set into road/sidewalk. Often has text/municipal emblems.",
        "Pothole": "Road surface depression/damage. Irregular dark hole in pavement. Often filled with water after rain. Exposes underlying road layers.",
        "Street Light": "Tall pole with mounted illumination fixture. Extends above roads/sidewalks. Light housing at top, sometimes with multiple heads/arms.",
        "Pole": "Slender vertical support structure. Metal/wood, cylindrical/rectangular. Used for signs, lights, without mounted objects.",
        "Traffic Sign Frame": "Large metal structure supporting road signs. Multiple poles supporting wide sign panels. Common on highways/intersections.",
        "Utility Pole": "Tall wooden/concrete pole carrying wires. Has electrical cables, transformers, sometimes with streetlights or communication equipment.",
        "Traffic Light": "Signal device controlling traffic flow. Red/yellow/green lights in housing. Various orientations, without support pole.",
        "Traffic Sign (Back)": "Rear side of road sign. Plain metal surface, usually gray/galvanized. Visible mounting brackets/supports.",
        "Traffic Sign (Front)": "Information display for road users. Distinctive shapes/colors (red octagons, yellow diamonds, etc). Contains symbols/text.",
        "Trash Can": "Waste receptacle in public areas. Cylindrical/rectangular container with opening/lid. Various colors, often secured to ground/poles."
    },
    "o1": {
        "Curb": "Raised (>3cm) edge at the boundary between road and sidewalk/terrain, with a vertical face and sometimes a horizontal top.",
        "Fence": "Freestanding barrier featuring spaced bars or panels, separating adjacent areas.",
        "Guard Rail": "Metal railing commonly positioned along roads, incorporating bars or posts.",
        "Barrier": "Block-like structure placed to separate or obstruct passage (e.g., jersey divider).",
        "Wall": "Standalone partition bounding or dividing outdoor spaces, possibly transparent.",
        "Bike Lane": "Narrow paved strip visually distinct from the main road, set for bicycle use.",
        "Crosswalk - Plain": "Street crossing marked by two parallel lines, lacking zebra stripes.",
        "Curb Cut": "Lowered (~3cm) curb or small ramp at sidewalk edges for smoother transitions.",
        "Parking": "Paved area set apart from the main roadway, used for stationary vehicles.",
        "Pedestrian Area": "Walkable zone away from vehicular lanes, found in city centers or parks.",
        "Rail Track": "Parallel steel rails on or embedded in the ground, often crossing or adjacent to roads.",
        "Road": "Primary paved surface for vehicles, typically flanked by curbs or marked lanes.",
        "Service Lane": "Extra roadside strip (often on highways) wide enough for a stopped vehicle.",
        "Sidewalk": "Elevated or bordered pedestrian path alongside roads, sometimes shared with cyclists.",
        "Bridge": "Elevated structure spanning a gap, including any attached railings or panels.",
        "Building": "Vertical construction with walls and a roof, possibly featuring glass or scaffolding.",
        "Tunnel": "Enclosed passage with an overhead cover, dim interior walls/ceiling visible from outside.",
        "Lane Marking - Crosswalk": "Painted zebra stripes forming a pedestrian crossing on the roadway.",
        "Lane Marking - General": "Painted road markings such as lines, arrows, or stop bars.",
        "Catch Basin": "Grate or inlet at curb/road level providing an opening to a drainage channel.",
        "Fire Hydrant": "Compact metal cylinder on the roadside with protruding caps/nozzles.",
        "Junction Box": "Rectangular enclosure (metal/plastic), usually near sidewalks or poles, containing wiring.",
        "Manhole": "Round or square cover flush with pavement, giving underground access.",
        "Pothole": "Depression or hole in the road surface, uneven in shape or depth.",
        "Street Light": "Light fixture mounted atop a tall pole, typically over roads or pathways.",
        "Pole": "Vertical shaft supporting other items (e.g., lights/signs), distinct from attachments.",
        "Traffic Sign Frame": "Metal framework, often overhead, that supports large road signs.",
        "Utility Pole": "Tall post for carrying overhead wires or equipment, occasionally with mounted lights.",
        "Traffic Light": "Enclosure containing colored lights near roads or intersections, typically facing traffic.",
        "Traffic Sign (Back)": "Rear side of a sign panel, generally plain or showing mounting hardware.",
        "Traffic Sign (Front)": "Front side of a sign panel displaying symbols or text, often reflective.",
        "Trash Can": "Outdoor receptacle with an opening or lid, typically placed along sidewalks or public areas."
    }
}